modLoader="javafml"
loaderVersion="[39,)"
license="All rights reserved"
issueTrackerURL="https://github.com/Leronus/mOres/issues"
[[mods]]
modId="mores"
version="${file.jarVersion}"
displayName="mOres"
displayURL="https://www.curseforge.com/minecraft/mc-mods/mores-by-its-infinite"
logoFile="mores_logo.png"
credits="Hypnosheep - Wiki"
authors="Leronus"
description='''
This mod adds tons of new tools, weapons and materials.

This improves combat, exploration, and mining in particular.

It adds much more variety and is very entertaining to play with friends.
'''
[[dependencies.mores]]
    modId="forge"
    mandatory=true
    versionRange="[39,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.mores]]
    modId="minecraft"
    mandatory=true
# This version range declares a minimum of the current minecraft version up to but not including the next major version
    versionRange="[1.18.1,1.19)"
    ordering="NONE"
    side="BOTH"
