modLoader="javafml" #mandatory
loaderVersion="[46,)" #mandatory
license="All rights reserved"
issueTrackerURL="https://github.com/Leronus/mOres/issues"
# A list of mods - how many allowed here is determined by the individual mod loader
[[mods]] #mandatory
modId="mores" #mandatory
version="${file.jarVersion}" #mandatory
displayName="mOres" #mandatory
# A URL to query for updates for this mod. See the JSON update specification https://mcforge.readthedocs.io/en/latest/gettingstarted/autoupdate/
#updateJSONURL="https://change.me.example.invalid/updates.json" #optional
# A URL for the "homepage" for this mod, displayed in the mod UI
displayURL="https://www.curseforge.com/minecraft/mc-mods/mores-by-its-infinite" #optional
# A file name (in the root of the mod JAR) containing a logo for display
logoFile="mores_logo.png" #optional
credits="HypnoSheep, BramTerlouw" #optional
authors="Leronus" #optional
displayTest="MATCH_VERSION"
description='''
This mod adds tons of new tools, weapons and materials.

This improves combat, exploration, and mining in particular.

It adds much more variety and is very entertaining to play with friends.
'''
[[dependencies.mores]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[46,)" #mandatory
    ordering="AFTER"
    side="BOTH"
[[dependencies.mores]]
    modId="minecraft"
    mandatory=true
# This version range declares a minimum of the current minecraft version up to but not including the next major version
    versionRange="[1.20,)"
    ordering="AFTER"
    side="BOTH"
