//// Date: 14-5-2015 17:17:20
//// Template version 1.1
//// Java generated by Techne
//// Keep in mind that you still need to fill in some blanks
//// - ZeuX
//
//
//
//
//
//
//package net.minecraft.src;
//
//public class ModelModel extends ModelBase
//{
//  //fields
//    ModelRenderer LegLeft;
//    ModelRenderer FeetLeft1;
//    ModelRenderer FeetLeft2;
//    ModelRenderer LegRight;
//    ModelRenderer FeetRight1;
//    ModelRenderer FeetRight2;
//    ModelRenderer Body;
//    ModelRenderer Wing1;
//    ModelRenderer Wing2;
//    ModelRenderer Head;
//    ModelRenderer Mouth;
//
//  public ModelModel()
//  {
//    textureWidth = 64;
//    textureHeight = 32;
//
//      LegLeft = new ModelRenderer(this, 12, 12);
//      LegLeft.addBox(0F, 0F, 0F, 1, 5, 0);
//      LegLeft.setRotationPoint(-2F, 19F, 0F);
//      LegLeft.setTextureSize(64, 32);
//      LegLeft.mirror = true;
//      setRotation(LegLeft, 0F, 0F, 0F);
//      FeetLeft1 = new ModelRenderer(this, 0, 13);
//      FeetLeft1.addBox(0F, 5F, -1F, 1, 0, 1);
//      FeetLeft1.setRotationPoint(-2F, 19F, 0F);
//      FeetLeft1.setTextureSize(64, 32);
//      FeetLeft1.mirror = true;
//      setRotation(FeetLeft1, 0F, 0F, 0F);
//      FeetLeft2 = new ModelRenderer(this, 0, 15);
//      FeetLeft2.addBox(-1F, 5F, -3F, 3, 0, 2);
//      FeetLeft2.setRotationPoint(-2F, 19F, 0F);
//      FeetLeft2.setTextureSize(64, 32);
//      FeetLeft2.mirror = true;
//      setRotation(FeetLeft2, 0F, 0F, 0F);
//      LegRight = new ModelRenderer(this, 12, 12);
//      LegRight.addBox(0F, 0F, 0F, 1, 5, 0);
//      LegRight.setRotationPoint(1F, 19F, 0F);
//      LegRight.setTextureSize(64, 32);
//      LegRight.mirror = true;
//      setRotation(LegRight, 0F, 0F, 0F);
//      FeetRight1 = new ModelRenderer(this, 0, 13);
//      FeetRight1.addBox(0F, 5F, -1F, 1, 0, 1);
//      FeetRight1.setRotationPoint(1F, 19F, 0F);
//      FeetRight1.setTextureSize(64, 32);
//      FeetRight1.mirror = true;
//      setRotation(FeetRight1, 0F, 0F, 0F);
//      FeetRight2 = new ModelRenderer(this, 0, 15);
//      FeetRight2.addBox(-1F, 5F, -3F, 3, 0, 2);
//      FeetRight2.setRotationPoint(1F, 19F, 0F);
//      FeetRight2.setTextureSize(64, 32);
//      FeetRight2.mirror = true;
//      setRotation(FeetRight2, 0F, 0F, 0F);
//      Body = new ModelRenderer(this, 0, 18);
//      Body.addBox(0F, 0F, 0F, 6, 6, 8);
//      Body.setRotationPoint(-3F, 13F, -5F);
//      Body.setTextureSize(64, 32);
//      Body.mirror = true;
//      setRotation(Body, 0F, 0F, 0F);
//      Wing1 = new ModelRenderer(this, 44, 22);
//      Wing1.addBox(0F, 0F, -3F, 1, 4, 6);
//      Wing1.setRotationPoint(-4F, 13F, -1F);
//      Wing1.setTextureSize(64, 32);
//      Wing1.mirror = true;
//      setRotation(Wing1, 0F, 0F, 0F);
//      Wing2 = new ModelRenderer(this, 44, 11);
//      Wing2.addBox(0F, 0F, -3F, 1, 4, 6);
//      Wing2.setRotationPoint(3F, 13F, -1F);
//      Wing2.setTextureSize(64, 32);
//      Wing2.mirror = true;
//      setRotation(Wing2, 0F, 0F, 0F);
//      Head = new ModelRenderer(this, 29, 23);
//      Head.addBox(-2F, -5F, -3F, 4, 6, 3);
//      Head.setRotationPoint(0F, 14F, -4F);
//      Head.setTextureSize(64, 32);
//      Head.mirror = true;
//      setRotation(Head, 0F, 0F, 0F);
//      Mouth = new ModelRenderer(this, 30, 18);
//      Mouth.addBox(-2F, -3F, -5F, 4, 2, 2);
//      Mouth.setRotationPoint(0F, 14F, -4F);
//      Mouth.setTextureSize(64, 32);
//      Mouth.mirror = true;
//      setRotation(Mouth, 0F, 0F, 0F);
//  }
//
//  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
//  {
//    super.render(entity, f, f1, f2, f3, f4, f5);
//    setRotationAngles(f, f1, f2, f3, f4, f5);
//    LegLeft.render(f5);
//    FeetLeft1.render(f5);
//    FeetLeft2.render(f5);
//    LegRight.render(f5);
//    FeetRight1.render(f5);
//    FeetRight2.render(f5);
//    Body.render(f5);
//    Wing1.render(f5);
//    Wing2.render(f5);
//    Head.render(f5);
//    Mouth.render(f5);
//  }
//
//  private void setRotation(ModelRenderer model, float x, float y, float z)
//  {
//    model.rotateAngleX = x;
//    model.rotateAngleY = y;
//    model.rotateAngleZ = z;
//  }
//
//  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5)
//  {
//    super.setRotationAngles(f, f1, f2, f3, f4, f5);
//  }
//
//}
